- name: Set zk_host_list variable
  set_fact:
    zk_host_list: []
- name: setting zk hosts
  set_fact:
    zk_host_list: "{{ zk_host_list }} + [ '{{ item }}' ]"
  with_items:
    "{{ groups['ec2_group'] }}"
  register: zk_host_list
- name: Set zk_host_port_list variable
  set_fact:
    zk_host_port_list: []
- name: setting zk host:port
  set_fact:
    zk_host_port_list: "{{ zk_host_port_list }} + [ '{{ item }}' + ':2888:3888' ]"
  with_items:
    "{{ groups['ec2_group'] }}"
  register: zk_host_port_list
- name: Set kafka_zk_host_port_list variable
  set_fact:
    kafka_zk_host_port_list: []
- name: setting kafka zk host:port
  set_fact:
    kafka_zk_host_port_list: "{{ kafka_zk_host_port_list }} + [ '{{ item }}' + ':2181' ]"
  with_items:
    "{{ groups['ec2_group'] }}"
  register: kafka_zk_host_port_list
- name: Set kafka_host_port_list variable
  set_fact:
    kafka_host_port_list: []
- name: setting kafka host:port
  set_fact:
    kafka_host_port_list: "{{ kafka_host_port_list }} + [ '{{ item }}' + ':9092' ]"
  with_items:
    "{{ groups['ec2_group'] }}"
  register: kafka_host_port_list